# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CloudCoreExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CloudCore', :path => '../'
  
  # Pods for CloudCoreExample
  pod 'Fakery', '~> 3.3.0'
  pod 'Connectivity'
end
